---
version: "1.4.10-6"

default-factions-plugin: FactionsPro

enable-multiworld-chat: false

# Available PureChat Tags: {display_name}, {msg}, {fac_name}, {fac_rank}, {prefix}, {suffix}, {world}
groups:
  Guest:
    chat: '&7[Guest] &f{fac_rank}{fac_name}&a {display_name} &7> &f{msg}'
    nametag: '&7[Guest] &f{display_name}'
    worlds: []
...
